import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <header className="custom-font w-full flex justify-between items-center p-4 border-b shadow-sm bg-white">          <div className="flex-1"></div>
          <nav className="flex gap-6 justify-center">
            <button className="text-gray-800 hover:text-blue-500 text-lg">
              Resume</button>

            <button className="text-gray-800 hover:text-blue-500 text-lg">
              Socials</button>

            <button className="text-gray-800 hover:text-blue-500 text-lg">
              Home</button>

          </nav>
          <div className="flex-1 flex justify-end">
            <button className="text-gray-800 hover:text-blue-500 text-lg">
              Projects</button>
          </div>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
